server:
  port: 8080
  url: http://localhost:${server.port}

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      client-id: token-keys-client
      client-secret: secret
    clients:
      messaging-app-client:
        client-id: messaging-app-client
        client-secret: secret
        user-authorization-uri: ${server.url}/oauth/authorize
        access-token-uri: ${server.url}/oauth/token
        scope: message.read, message.write
        pre-established-redirect-uri: ${server.url}/messaging
    resource:
      jwk-set-uri: https://uaa.run.pivotal.io/token_keys

messages:
  base-uri: ${server.url}/messages
